Add live variable analysis.
xingweitian/checker-framework pull request #5
Opened 2019-11-08 02:59 UTC by xingweitian

2019-11-26 00:32 UTC, wmdietl requested changes
Thanks for working on this!

2019-11-26 00:32 UTC, wmdietl commented on dataflow/src/main/java/org/checkerframework/dataflow/livevariable/LiveVar.java
> +/** The live variable class. */
Javadoc like this isn't particularly useful, it only expands the class name.
Can you give interesting information?

2019-11-26 00:32 UTC, wmdietl commented on dataflow/src/main/java/org/checkerframework/dataflow/livevariable/LiveVar.java
> +    Node liveNode;
It is a bit surprising that a live "variable" tracks a Node. Which node is this? The declaration of the variable? The most recent assignment?

2019-11-26 00:32 UTC, wmdietl commented on dataflow/src/main/java/org/checkerframework/dataflow/livevariable/LiveVar.java
> +    Node liveNode;
Can this field be protected and final?

2019-11-26 00:32 UTC, wmdietl commented on dataflow/src/main/java/org/checkerframework/dataflow/livevariable/LiveVariableStore.java
> +    private Set<LiveVar> liveVarSet;
Can this be final?

2019-11-26 00:32 UTC, wmdietl commented on dataflow/src/main/java/org/checkerframework/dataflow/livevariable/LiveVariableStore.java
> +public class LiveVariableStore implements Store<LiveVariableStore> {
The naming seems a bit inconsistent... why is this not `LiveVarStore`? Or should `LiveVar` be `LiveVariable`?

2019-11-26 00:32 UTC, wmdietl commented on dataflow/src/main/java/org/checkerframework/dataflow/livevariable/LiveVariableStore.java
> +    public void addUseInExpression(Node expression) {
Would it be easier to use a new subclass of https://github.com/typetools/checker-framework/blob/master/dataflow/src/main/java/org/checkerframework/dataflow/cfg/node/AbstractNodeVisitor.java for this?

2019-11-26 00:32 UTC, wmdietl commented on dataflow/src/main/java/org/checkerframework/dataflow/livevariable/LiveVariableStore.java
> +        Set<LiveVar> liveVarSetLub = new HashSet<>();
How large will these sets become? Is it worth setting the initial capacity?

2019-11-26 00:32 UTC, wmdietl commented on dataflow/src/main/java/org/checkerframework/dataflow/livevariable/LiveVariableStore.java
> +            return sbStoreVal.toString();
Move the isEmpty check before you create the StringBuffer and directly write `return "null"`.
Instead of "null" something else is probably less ambiguous and misleading... "no live variables" maybe?

2019-11-26 00:32 UTC, wmdietl commented on dataflow/src/main/java/org/checkerframework/dataflow/cfg/CFGVisualizer.java
> +    String visualizeStoreVal(Object value);
It's not really clear what this method is for. Is this just to get quoting and escaping of the string right?
Can you think of a better name and then maybe use the method more widely?

2020-02-03 00:05 UTC, closed without merging

2020-03-25 04:17 UTC, xingweitian commented on dataflow/src/main/java/org/checkerframework/dataflow/livevariable/LiveVar.java
> +    Node liveNode;
Yes, the node can be a `LocalVariableNode` or `FieldAccessNode`.